In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

In [2]:
df=pd.read_csv('data/gemstone.csv')
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [3]:
df=df.drop(labels=['id'],axis=1)

In [4]:
X=df.drop(labels=['price'],axis=1)
y=df[['price']]

In [5]:
categorical_col=X.select_dtypes(include='object').columns
numerical_cols=X.select_dtypes(exclude='object').columns
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OrdinalEncoder
from sklearn.pipeline import Pipeline

num_pipeline= Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])
cat_pipeline= Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ordinal_encode',OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories])),
    ('scaler',StandardScaler())
])

preprocessor=ColumnTransformer([
    ("num_pipeline",num_pipeline,numerical_cols),
    ("cat_pipeline",cat_pipeline,categorical_col)
])

C:\Users\sivan\AppData\Local\Temp\ipykernel_5160\1884209073.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_col=X.select_dtypes(include='object').columns

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [8]:
print(X_train.columns)

Index(['num_pipeline__carat', 'num_pipeline__depth', 'num_pipeline__table',
       'num_pipeline__x', 'num_pipeline__y', 'num_pipeline__z',
       'cat_pipeline__cut', 'cat_pipeline__color', 'cat_pipeline__clarity'],
      dtype='str')

In [9]:
X_train.head()

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-1.016395,-0.204317,0.402608,-1.202472,-1.187395,-1.194148,-0.132842,-0.936018,-0.648950
1,0.882396,0.720758,-0.118536,0.985177,0.941823,1.036109,-0.132842,-0.320002,0.017052
2,1.529711,0.350728,-1.160823,1.426308,1.394848,1.441611,0.872563,1.528047,0.017052
3,1.896523,0.073206,0.923751,1.741402,1.711965,1.702290,-0.132842,1.528047,-1.314953
4,0.450852,1.738340,1.444895,0.562052,0.525040,0.703019,-2.143651,0.912031,0.017052

In [10]:
def evaluate_model(true,predict):
    mae=mean_absolute_error(true,predict)
    mse=mean_squared_error(true,predict)
    rmse=np.sqrt(mean_squared_error(true,predict))
    r2=r2_score(true,predict)
    return mae,mse,rmse,r2

In [11]:
models={
    'Linear_regression':LinearRegression(),
    'lasso':Lasso(),
    'ridge':Ridge(),
    'decision_tree':DecisionTreeRegressor(),
    'random_forest':RandomForestRegressor(),
    'kneighbour':KNeighborsRegressor(),
    'xgboost':XGBRegressor(),
    'adaboost':AdaBoostRegressor(),
    'catboost':CatBoostRegressor(verbose=False)
}
model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train.values.flatten())

    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- Mean squared error: {:.4f}".format(model_train_mse))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- Mean squared error: {:.4f}".format(model_test_mse))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear_regression
Model performance for Training set
- Root Mean Squared Error: 1016.9490
- Mean Absolute Error: 677.1656
- Mean squared error: 1034185.3253
- R2 Score: 0.9366
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 1006.6010
- Mean Absolute Error: 671.5856
- Mean squared error: 1013245.5453
- R2 Score: 0.9373
===================================


lasso
Model performance for Training set
- Root Mean Squared Error: 1017.0718
- Mean Absolute Error: 678.3145
- Mean squared error: 1034434.9530
- R2 Score: 0.9366
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 1006.8716
- Mean Absolute Error: 672.8635
- Mean squared error: 1013790.3799
- R2 Score: 0.9373
===================================


ridge
Model performance for Training set
- Root Mean Squared Error: 1016.9491
- Mean Absolute Error: 677.1925
- Mean squared error: 1034185.4419
- R2 Score: 0.9366
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 1006.6062
- Mean Absolute Error: 671.6137
- Mean squared error: 1013256.1052
- R2 Score: 0.9373
===================================


decision_tree
Model performance for Training set
- Root Mean Squared Error: 12.8816
- Mean Absolute Error: 0.8012
- Mean squared error: 165.9367
- R2 Score: 1.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 829.5851
- Mean Absolute Error: 421.7847
- Mean squared error: 688211.4033
- R2 Score: 0.9574
===================================


random_forest
Model performance for Training set
- Root Mean Squared Error: 227.6727
- Mean Absolute Error: 115.8942
- Mean squared error: 51834.8488
- R2 Score: 0.9968
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 606.4252
- Mean Absolute Error: 309.7448
- Mean squared error: 367751.4964
- R2 Score: 0.9772
===================================


kneighbour
Model performance for Training set
- Root Mean Squared Error: 545.6568
- Mean Absolute Error: 285.8191
- Mean squared error: 297741.3103
- R2 Score: 0.9817
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 671.2868
- Mean Absolute Error: 349.4662
- Mean squared error: 450626.0243
- R2 Score: 0.9721
===================================


xgboost
Model performance for Training set
- Root Mean Squared Error: 514.2452
- Mean Absolute Error: 275.7583
- Mean squared error: 264448.1250
- R2 Score: 0.9838
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 585.4372
- Mean Absolute Error: 296.9582
- Mean squared error: 342736.6875
- R2 Score: 0.9788
===================================


adaboost
Model performance for Training set
- Root Mean Squared Error: 1311.1370
- Mean Absolute Error: 894.7102
- Mean squared error: 1719080.1761
- R2 Score: 0.8946
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 1314.7779
- Mean Absolute Error: 894.5643
- Mean squared error: 1728640.9420
- R2 Score: 0.8930
===================================


catboost
Model performance for Training set
- Root Mean Squared Error: 530.6367
- Mean Absolute Error: 282.2494
- Mean squared error: 281575.3113
- R2 Score: 0.9827
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 579.9574
- Mean Absolute Error: 295.4844
- Mean squared error: 336350.5737
- R2 Score: 0.9792
===================================

In [12]:
df_results=pd.DataFrame(list(zip(model_list,r2_list)),columns=['Model_Name','r2_score']).sort_values(by=['r2_score'],ascending=False)
df_results

          Model_Name  r2_score
8           catboost  0.979186
6            xgboost  0.978790
4      random_forest  0.977243
5         kneighbour  0.972114
3      decision_tree  0.957412
0  Linear_regression  0.937298
2              ridge  0.937297
1              lasso  0.937264
7           adaboost  0.893027

In [13]:
cbr = CatBoostRegressor(verbose=False)

param_dist = {
    'depth': [4,5,6,7,8,9,10],
    'learning_rate': [0.01,0.02,0.03,0.04],
    'iterations': [300,400,500,600]
}

rscv = RandomizedSearchCV(cbr, param_dist, cv=5, n_jobs=-1, scoring='r2')

rscv.fit(X_train, y_train.values.flatten())

print(rscv.best_params_)
print(rscv.best_score_)

{'learning_rate': 0.04, 'iterations': 600, 'depth': 9}
0.9797888194337947

In [14]:
def print_evaluated(model,X_train,y_train,X_test,y_test):
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- Mean squared error: {:.4f}".format(model_train_mse))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- Mean squared error: {:.4f}".format(model_test_mse))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

In [15]:
best_cbr=rscv.best_estimator_
print_evaluated(best_cbr,X_train,y_train,X_test,y_test)

Model performance for Training set
- Root Mean Squared Error: 542.0852
- Mean Absolute Error: 286.6947
- Mean squared error: 293856.3246
- R2 Score: 0.9820
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 575.6947
- Mean Absolute Error: 294.4484
- Mean squared error: 331424.3762
- R2 Score: 0.9795
===================================

In [18]:
from sklearn.model_selection import GridSearchCV
# Initialize knn
knn = KNeighborsRegressor()

# parameters
k_range = list(range(2, 10))
param_grid = dict(n_neighbors=k_range)

# Fitting the cvmodel
grid = GridSearchCV(knn, param_grid, cv=5, scoring='r2',n_jobs=-1)
grid.fit(X_train, y_train)

# Print the tuned parameters and score
print(grid.best_params_)
print(grid.best_score_)

{'n_neighbors': 9}
0.9732360138108191

In [25]:
best_knn = grid.best_estimator_

print_evaluated(best_knn, X_train, y_train, X_test, y_test)

Model performance for Training set
- Root Mean Squared Error: 583.6237
- Mean Absolute Error: 304.8179
- Mean squared error: 340616.6086
- R2 Score: 0.9791
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 651.6384
- Mean Absolute Error: 339.6234
- Mean squared error: 424632.6030
- R2 Score: 0.9737
===================================

In [26]:
# Initializing xgboost
xgb = XGBRegressor()

# Parameters
params = {
 'learning_rate' : [0.05,0.10,0.15,0.20,0.25,0.30],
 'max_depth' : [ 3, 4, 5, 6, 8, 10, 12, 15],
 'min_child_weight' : [ 1, 3, 5, 7 ],
 'gamma': [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
 'colsample_bytree' : [ 0.3, 0.4, 0.5 , 0.7 ],
 'n_estimators':[300,400,500,600]
}

rs_xgb=RandomizedSearchCV(xgb,param_distributions=params,scoring='r2',n_jobs=-1,cv=5)
rs_xgb.fit(X_train, y_train.values.flatten())

# Print the tuned parameters and score
print(rs_xgb.best_params_)
print(rs_xgb.best_score_)

{'n_estimators': 300, 'min_child_weight': 7, 'max_depth': 6, 'learning_rate': 0.05, 'gamma': 0.0, 'colsample_bytree': 0.5}
0.9796492576599121

In [ ]:
# Selecting best xgb model
best_xgb = rs_xgb.best_estimator_

# Evaluate Train and Test dataset
print_evaluated_results(best_xgb,X_train,y_train,X_test,y_test)

In [ ]:
from sklearn.ensemble import votingRegressor
er=votingRegressor([('cbr',best_cbr),()])

In [ ]:
feature_imp=best_cbr.feature_importance_
feature_nm= best_cbr.feature_names_
imp_series=pd.series(feature_imp)
imp_series.index=feature_nm
print(imp_series.sort_values(ascending=False))
print('\n')
imp_series.sort_values().plot(kind='bar',
xlabel='feature importance',
                              ylabel='feature name',
                              title='Catboost Feature importances')
plt.show()